version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./data:/data
      - ./app:/app/app   # allow live edit from host
      - ./ddialog.db:/app/ddialog.db
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis

  worker:
    build: .
    command: uv run celery -A app.celery_app worker --loglevel=info --concurrency=1 -Q default
    volumes:
      - ./data:/data
      - ./app:/app/app
      - ./ddialog.db:/app/ddialog.db
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis
      - web
