"""Initial schema

Revision ID: 001
Revises:
Create Date: 2024-09-19 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create videos table
    op.create_table('videos',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('original_filename', sa.String(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('duration', sa.Float(), nullable=True),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('format', sa.String(), nullable=True),
        sa.Column('mime_type', sa.String(), nullable=False),
        sa.Column('upload_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_filename'), 'videos', ['filename'], unique=False)
    op.create_index(op.f('ix_videos_upload_time'), 'videos', ['upload_time'], unique=False)

    # Create processed_videos table
    op.create_table('processed_videos',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('original_video_id', sa.String(length=36), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('processing_type', sa.String(), nullable=False),
        sa.Column('processing_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('quality', sa.String(), nullable=True),
        sa.Column('duration', sa.Float(), nullable=True),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['original_video_id'], ['videos.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_videos_created_at'), 'processed_videos', ['created_at'], unique=False)
    op.create_index(op.f('ix_processed_videos_original_video_id'), 'processed_videos', ['original_video_id'], unique=False)
    op.create_index(op.f('ix_processed_videos_processing_type'), 'processed_videos', ['processing_type'], unique=False)

    # Create jobs table
    op.create_table('jobs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('video_id', sa.String(length=36), nullable=False),
        sa.Column('job_type', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('progress', sa.Integer(), nullable=True),
        sa.Column('result_file_path', sa.String(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_video_id'), 'jobs', ['video_id'], unique=False)

    # Create overlays table
    op.create_table('overlays',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('processed_video_id', sa.String(length=36), nullable=False),
        sa.Column('overlay_type', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('position_x', sa.Integer(), nullable=True),
        sa.Column('position_y', sa.Integer(), nullable=True),
        sa.Column('start_time', sa.Float(), nullable=True),
        sa.Column('end_time', sa.Float(), nullable=True),
        sa.Column('font_size', sa.Integer(), nullable=True),
        sa.Column('font_color', sa.String(), nullable=True),
        sa.Column('language', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['processed_video_id'], ['processed_videos.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overlays_overlay_type'), 'overlays', ['overlay_type'], unique=False)
    op.create_index(op.f('ix_overlays_processed_video_id'), 'overlays', ['processed_video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_overlays_processed_video_id'), table_name='overlays')
    op.drop_index(op.f('ix_overlays_overlay_type'), table_name='overlays')
    op.drop_table('overlays')
    op.drop_index(op.f('ix_jobs_video_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_processed_videos_processing_type'), table_name='processed_videos')
    op.drop_index(op.f('ix_processed_videos_original_video_id'), table_name='processed_videos')
    op.drop_index(op.f('ix_processed_videos_created_at'), table_name='processed_videos')
    op.drop_table('processed_videos')
    op.drop_index(op.f('ix_videos_upload_time'), table_name='videos')
    op.drop_index(op.f('ix_videos_filename'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
